[package]
name = "octox_macros"
edition = "2024"
version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
proc-macro = true
name = "derive"
path = "lib.rs"

[dependencies]

[features]
default = []
kernel = []
user = []
